// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.196
// </auto-generated>
// ------------------------------------------------------------------------------
namespace W3cValidator
{
    static class Vsix
    {
        public const string Id = "5f8512da-c0df-4703-b72b-1d67315dd560";
        public const string Name = "W3C Validator";
        public const string Description = @"Validates any ASP.NET web application using the W3C validator on the rendered DOM running in the browser";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "w3c, validation, browser link";
    }
}
