// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.196
// </auto-generated>
// ------------------------------------------------------------------------------
namespace W3cValidator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "9ca84552-a726-43e2-acc4-dd57f666aed2";
        public const string guidAutoLoadString = "30be1e3d-281b-4fa6-b1ef-7652b84edb60";
        public const string guidValidatorPackageCmdSetString = "1a2df5ea-d879-4520-a28f-87ebfe1453e6";
        public const string guidBrowserLinkCmdSetString = "30947ebe-9147-45f9-96cf-401bfc671a82";
        public static Guid guidPackage = new Guid(guidPackageString);
        public static Guid guidAutoLoad = new Guid(guidAutoLoadString);
        public static Guid guidValidatorPackageCmdSet = new Guid(guidValidatorPackageCmdSetString);
        public static Guid guidBrowserLinkCmdSet = new Guid(guidBrowserLinkCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int EnableValidationId = 0x0100;
        public const int IDG_BROWSERLINK_COMMANDS = 0x2001;
    }
}
